services:
#  app:
#    container_name: booklending-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "${PUBLISHED_PORT}:9090"
#    env_file:
#      - .env
#    mem_limit: 1024m
#    mem_reservation: 300m
#    cpus: 1.0
#    environment:
#      DB_HOST: postgres-db
#      JAVA_OPTS: >
#        -XX:ActiveProcessorCount=1
#        -XX:MaxRAMPercentage=60
#        -XX:InitialRAMPercentage=40
#        -XX:+UseG1GC
#        -XX:+ExitOnOutOfMemoryError
#    depends_on:
#      postgres-db:
#        condition: service_healthy
#    networks:
#      - net-booklending

  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: booklending
      POSTGRES_PASSWORD: booklending@123
      POSTGRES_DB: booklending
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booklending -d booklending"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - net-booklending

volumes:
  postgres_data:

networks:
  net-booklending:
    driver: bridge